source 'http://rubygems.org'
gem 'json',     '~> 1.1.9'
gem 'rack',     '~> 1.2.1'
gem 'wlang',    '~> 0.9.1'
gem 'waw',      '~> 0.3.0'
gem 'RedCloth', '~> 4.2.2'
gem 'sequel',   '~> 3.8.0'
gem 'pg',       '~> 0.8.0'
gem 'rubyrel',  '~> 0.0.3'
